Parameters:    
  ManagedPolicy:
    Type: String
    Default: AmazonEC2ContainerServiceforEC2Role
    
  Service:
    Type: String
    Default: ec2.amazonaws.com
    
  S3TemplateUrl:
    Type: String
    Default: https://s3-ap-southeast-2.amazonaws.com/cfn-template-ctc94
    Description: S3Template directory.
Resources:
#  ServiceRole:
#    Type: AWS::IAM::Role
#    Properties:
#      Path: /
#      AssumeRolePolicyDocument: !Sub |
#        {
#            "Statement": [{
#                "Effect": "Allow",
#                "Principal": { "Service": [ "${Service}" ]},
#                "Action": [ "sts:AssumeRole" ]
#            }]
#        }
#      ManagedPolicyArns:
#        - !Sub arn:aws:iam::aws:policy/service-role/${ManagedPolicy}
  ServiceRole:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${S3TemplateUrl}/basic/ServiceRole.yml
      Parameters:
        Service: ec2.amazonaws.com
        ManagedPolicy: AmazonEC2ContainerServiceforEC2Role

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !GetAtt ServiceRole.Outputs.ServiceRole

Outputs: 
  InstanceProfile: 
      Value: !Ref InstanceProfile