Parameters:
  Name:
    Type: String

  VpcId:
    Type: String
    
Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref Name

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VpcId      
      
Outputs:
   GatewayId:
      Value: !Ref InternetGateway