Parameters:
  Name:
    Type: String
    Default: StandAlone-InternetGateway
    
  VpcId:
    Type: AWS::EC2::VPC::Id
    
Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref Name

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VpcId      
      
Outputs:
   GatewayId:
      Value: !Ref InternetGateway