Parameters:
  Name:
    Type: String
    
  VpcId:
    Type: String
    
  idx:
    Type: Number
    
  SubnetCIDR:
    Type: String

  RouteTableId:
    Type: String
 
Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ !Ref idx, !GetAZs ]
      MapPublicIpOnLaunch: true
      CidrBlock: !Ref SubnetCIDR
      Tags:
        - Key: Name
          Value: !Sub ${Name} (Public)
          
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableId
      SubnetId: !Ref Subnet

Outputs:
   SubnetId:
      Value: !Ref Subnet